### PR TITLE
Use schema-change-2017-q2 MB database image for testing

### PR DESCRIPTION
**Pull request by gentlecat**

### CODE REVIEW

**Comment by gentlecat** [comment]
Probably no need to merge this if current version will be on master. Putting this out for testing purposes.

This repo shouldn't require any changes for the next schema change, right @mwiencek?

**Comment by gentlecat** [comment]
Some kind of issue with the database creation:
```
mbs_db_test_1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/create_test_db.sh
mbs_db_test_1  | /home/musicbrainz/musicbrainz-server /home/musicbrainz/musicbrainz-server
mbs_db_test_1  | error: failed switching to "musicbrainz:musicbrainz": operation not permitted
```

**Comment by mwiencek** [comment]
We'll keep using the `schema-change-*` tags from now on, so we can merge this. This way we don't have to break old versions of the code anymore, it'll always reference an image it works with.

I fixed the `operation not permitted` error in https://github.com/metabrainz/musicbrainz-server/commit/04d13efdc6415373f0a8285573bdb546626cf15d and pushed a new image.

**Comment by gentlecat** [comment]
@brainzbot, test this please.

**Comment by gentlecat** [comment]
@brainzbot, test this please.

**Comment by gentlecat** [comment]
OK, great. Having separate version seems like a good idea. Perhaps we could also make `latest` the most recent release too, but I'll leave that up to you.

Tests seem to be passing now, so all good here.

**Comment by gentlecat** [comment]
@mwiencek, should we merge this now?

**Pull request merged**
