### PR TITLE
Development environment improvements

### PR DESCRIPTION
**Pull request by gentlecat**

### CODE REVIEW

**Comment by mwiencek** [comment]
I would think that for the docker setup we should be modifying docker/coverart_redirect.conf instead, if that's even used. The `.dist` version is referenced in the README.md for non-docker setups, and the current defaults look sane for that.

**Comment by gentlecat** [comment]
Hmm, it looks like *docker/coverart_redirect.conf* is unused. I'll remove it.

**Comment by gentlecat** [comment]
README.md should probably be updated as well. Would be easier to have one regularly maintained and supported way of running it in development.

**Comment by mwiencek** [comment]
Well, I think having manual setup information is still useful. The docker setup is nice for people who want to get up & running quickly and submit a small PR, but not useful for more involved development in my experience. You have to jump through all the docker hoops to do really simple things, so it's a pain to use for more than one-off PRs. Especially if you already have postgres running on your laptop, and just want to connect to that.

**Comment by gentlecat** [comment]
OK, sounds like a good use case. I'll refresh the old instructions then and add notes for Docker setup.

**Pull request merged**
